### ISSUE TITLE
denite is too slow on start time. 

### ISSUE THREAD

**Issue by ladieman217** [ctaylo21/jarvis#16]
I just feel it a little bit slow on start time when using `denite`. and I switch to coc-lists. It's much better and faster. maybe It's worth a try.
![image](https://user-images.githubusercontent.com/12859005/57898227-b6d8eb00-788a-11e9-94e2-e3de94fc0386.png)
[using coc-list](https://github.com/neoclide/coc.nvim/wiki/Using-coc-list)

**Comment by ctaylo21** [comment]
It's on my list to try! It would be great to reduce the total number of plugins as well.
