### ISSUE TITLE
Popup completion 

### ISSUE THREAD

**Issue by mr-tambourine-man** [ctaylo21/jarvis#19]
How can I make that beautiful popup show up when I'm coding, 
![image](https://user-images.githubusercontent.com/20029800/58577275-8004bc80-821c-11e9-9446-b15c9167f49f.png)

**Comment by mr-tambourine-man** [comment]
Solved

**Comment by ctaylo21** [comment]
For anyone else that has a similar issue, the [coc.nvim FAQ](https://github.com/neoclide/coc.nvim/wiki/F.A.Q) has some helpful steps for resolving issues with floating windows.
