### ISSUE TITLE
I can't find my init.vim and .zshrc anymore

### ISSUE THREAD

**Issue by phongloihong** [ctaylo21/jarvis#27]
Hi
After install Javis, I want to modify something but I can't find init.vim at ~/.config/nvim/init.vim any more.
.zshrc too, please help me.
Thanks alot

**Comment by ctaylo21** [comment]
Did you use the install script? If so, it should have copied them into your current directory into a folder called `backup`.

**Comment by ctaylo21** [comment]
I'm going to close this for now. Feel free to reopen if you think it's an issue with the script with some more details. Thanks!
