### ISSUE TITLE
Fix broken mappings in Denite

### ISSUE THREAD

**Issue by ctaylo21** [ctaylo21/jarvis#28]
Mappings that open files in new splits from normal mode in Denite are broken. User report:

```
CTRL + T from the denite fzf (LEADER + T) I get a "E73: tag stack empty"
```

**Comment by ducva** [comment]
In the nvim setting, he changed Leader key to ",". So I think you should try ",+t"

**Comment by ctaylo21** [comment]
This should be fixed now. The denite mappings changed so I had to update them to the new format.
