### ISSUE TITLE
Fixing 'caskroom/fonts was moved' error

### ISSUE THREAD

**Issue by storypixel** [ctaylo21/jarvis#33]
Hi, I am using your install.sh as a living guide to config neovim in a way that doesn't make me sad and I noticed

```
❯ brew tap caskroom/fonts
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

Error: caskroom/fonts was moved. Tap homebrew/cask-fonts instead.
```

Can I open a PR if you're busy to change `caskroom/fonts` to `homebrew/cask-fonts` assuming this helps?

**Comment by ctaylo21** [comment]
Absolutely! I stopped "officially" supporting that `install.sh` script because of the difficulty in keeping it up to date, but I'll always be happy to accept PR's to fix any issues.
