### ISSUE TITLE
Idea: using floating-preview for Denite

### ISSUE THREAD

**Issue by casperstorm** [ctaylo21/jarvis#38]
So, yeah this is technically not a issue but I just saw that Shogun added support for having a floating preview: https://github.com/Shougo/denite.nvim/blob/master/doc/denite.txt#L697.

It could be cool to create something similar to fzf, however just in Denite.
![image](https://user-images.githubusercontent.com/2248455/75428467-86110080-5948-11ea-96dd-d04557a36be2.png)

Do you have any idea how to do it, and how do you feel about it?

**Comment by ctaylo21** [comment]
You can just add 
```
\ 'floating_preview' : 1
```

to the `s:denite_options ` block and then add a mapping like:

```
  nnoremap <silent><buffer><expr> p
  \ denite#do_map('do_action', 'preview')
```
This will let you see a preview of a file by pressing `p` in the denite context.

It looks something like this in my current setup without any tweaking:
![image](https://user-images.githubusercontent.com/1427469/75495427-59bea980-5973-11ea-95bc-33a395b323c3.png)

I personally don't think I would use it much, and if I did I would have to tinker with the layout of the Denite popup window to figure out how to make it the most consistent. The current one is wide and doesn't leave much room for the preview window.

As for the preview window border, I would love that feature. I think most plugins are waiting on [neovim to support it](https://github.com/neovim/neovim/issues/9718).
