### ISSUE TITLE
Instructions for GNU/Linux?

### ISSUE THREAD

**Issue by i-oliva** [ctaylo21/jarvis#7]
Hi, I've seen the instructions section and you offer instructions for Windows/OSX... Is there any way Linux users can install this "minimal distro"? thanks!

**Comment by ctaylo21** [comment]
Some of these pieces are OSX only, but the bulk of the features are cross platform. 

## Neovim
I would start with installing [Neovim](https://github.com/neovim/neovim/wiki/Installing-Neovim) for your distro. Then, you can use the the `config/nvim/init.vim` file for your own Neovim setup. Once it's copied to your Neovim config, save it and source it.

You will likely have to install Python 3 and the Python 3/Neovim plugin. Something like this (depending on your distro).
```
sudo apt-get install python-neovim
sudo apt-get install python3-neovim
```

Then you should be able to open up Neovim and run
```
:PlugInstall
:UpdateRemotePlugins
```

This should get Neovim up and running.

## Tmux
Google how to install tmux for your distro. It could be something like 
```
sudo apt-get install tmux
```
or 
```
yum install tmux
```
or you could install from source. Then you can copy `tmux/tmux.conf.symlink` into wherever your OS's `tmux.conf` file is. Then save it, and source the file.

That gets you tmux + Neovim, which is the bulk of Jarvis. 

## Misc

Other than that, many of the "minimal" aspects of Jarvis can be recreated via your terminal. I use the [Oceanic Next](https://github.com/voronianski/oceanic-next-color-scheme) color scheme and ports of it are available in several different terminals/editors. 

The last main piece is to tweak your header/toolbar or any other menu that your OS shows to be hidden/minimal to only show the most important info. There are a lot of variations/tools to do this, and I would recommend a community like https://www.reddit.com/r/unixporn/ to get some ideas of how to customize your environment. Best of luck!

**Comment by ctaylo21** [comment]
I forgot another key piece. [Zsh](https://github.com/robbyrussell/oh-my-zsh) works on linux as well. So you can follow the linux install instructions on there and then use the config file from `zsh/zshrc.symlink` to copy to your OS's `.zshrc` file. 

Don't forget to install the awesome [Spaceship Prompt](https://github.com/denysdovhan/spaceship-prompt) to get an awesome prompt for your zsh setup!

**Comment by i-oliva** [comment]
Thanks!
