### ISSUE TITLE
Not able to navigate inside the Denite search results within nvim

### ISSUE THREAD

**Issue by ludovicianul** [ctaylo21/jarvis#9]
Although I'm able to invoke Deinte successfully either for searching files or buffers, I cannot navigate the search results. Is there a key combination I'm missing?

**Comment by ctaylo21** [comment]
You should be able to immediately start typing to filter the list, or you can press `<ctrl> + o` to switch to normal mode inside of a denite window so you can move around with the normal `h/j/k/l` keys and select the buffer you want with `<enter>`

**Comment by ludovicianul** [comment]
It works 👍 . Thanks for the quick answer.

**Comment by ctaylo21** [comment]
No problem, happy to help!
